version: '3.5'

services:
  postgres:
    container_name: chaingraph_postgres
    image: postgres:10.4
    volumes:
      - chaingraph-postgres-data-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      DB_NAME: chaingraph
      DB_USER: user
      DB_PASSWORD: pass
      POSTGRES_DB: chaingraph

  hasura:
    container_name: chaingraph_hasura
    image: hasura/graphql-engine:v1.3.3.cli-migrations-v2
    ports:
      - '8088:8080'
    depends_on:
      - postgres
    restart: always
    environment:
      # https://hasura.io/docs/1.0/graphql/core/deployment/graphql-engine-flags/reference.html
      HASURA_GRAPHQL_DATABASE_URL: postgres://user:pass@postgres:5432/chaingraph?sslmode=disable
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura-migrations
      HASURA_GRAPHQL_METADATA_DIR: /hasura-metadata
      # HASURA_GRAPHQL_ADMIN_SECRET: =NBc;?2eduh)?mxq
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_CORS_DOMAIN: '*'
      VIRTUAL_HOST: alpha.chaingraph.dev
      VIRTUAL_PORT: 8088
    networks:
      default:
        aliases:
          - alpha.chaingraph.dev
    volumes:
      - ./src/hasura/migrations:/hasura-migrations #  mount hasura migrations folder
      - ./src/hasura/metadata:/hasura-metadata #  mount hasura metadata folder
    command:
      - graphql-engine
      - serve

  core:
    container_name: chaingraph_core
    build:
      context: ./
    depends_on:
      - hasura
    environment:
      HASURA_API: ${HASURA_API}
      EOS_NODEOS_HOST: ${EOS_NODEOS_HOST}
      EOS_NODEOS_PORT: ${EOS_NODEOS_PORT}
      WAIT_HOSTS: ${HASURA_HOST}:8088
      WAIT_HOSTS_TIMEOUT: 60
    ports:
      - '3030:3030'

  nginx:
    container_name: chaingraph_nginx
    image: jwilder/nginx-proxy:alpine
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  chaingraph-postgres-data-volume:

networks:
  default:
    name: chaingraph
