version: '3.5'

services:
  chaingraph-postgres:
    container_name: chaingraph-postgres
    image: postgres:latest
    volumes: 
      - chaingraph-pgdata:/var/lib/postgresql/data_chaingraph
    ports:
      - '5432:5432'
    environment:
      PGPORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: chaingraph
      DB_NAME: chaingraph
      DB_USER: user
      DB_PASSWORD: pass

  chaingraph-hasura:
    container_name: chaingraph-hasura
    build: ./
    image: chaingraph-hasura:local
    ports:
      - "${HASURA_GRAPHQL_SERVER_PORT}:${HASURA_GRAPHQL_SERVER_PORT}"
    restart: always
    environment:
      # https://hasura.io/docs/1.0/graphql/core/deployment/graphql-engine-flags/reference.html
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_SERVER_PORT: ${HASURA_GRAPHQL_SERVER_PORT}
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_GRAPHQL_ENABLE_CONSOLE}
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_CORS_DOMAIN: "*"
      HASURA_GRAPHQL_AUTH_HOOK: ${HASURA_GRAPHQL_AUTH_HOOK}
      HASURA_GRAPHQL_AUTH_HOOK_MODE: ${HASURA_GRAPHQL_AUTH_HOOK_MODE}
      HASURA_GRAPHQL_ENABLED_APIS: ${HASURA_GRAPHQL_ENABLED_APIS}

    command:
      - graphql-engine
      - serve
    depends_on:
      - chaingraph-postgres

volumes:
  chaingraph-pgdata:

networks:
  default:
    name: chaingraph
    # driver: bridge

    