version: '3'

dotenv: ['.env']
silent: true

tasks:
  console:
    cmds:
      - hasura console --project services/hasura --console-port 8080

  seed:
    cmds:
      - hasura seeds apply --project services/hasura 
  
  up:
    cmds:
      - docker-compose up -d --build hasura nginx
      - docker-compose up -d --build nginx-letsencrypt nginx-gen
      - docker-compose restart nginx
      - docker-compose up -d --build core
  
  down:
    cmds:
      - docker-compose down -v --remove-orphans

  boot:
    cmds:
      - docker-compose up -d --build hasura nginx
      - sleep 60
      - hasura migrate apply --project services/hasura 
      - hasura metadata apply --project services/hasura 
      - hasura seeds apply --project services/hasura 
      - docker-compose up -d --build core
      - docker-compose up -d --build nginx-letsencrypt nginx-gen
      - docker-compose restart nginx

  boot-prod:
    cmds:
      - docker-compose -f docker-compose.prod.yml up -d --build hasura hasura-bitcash 
      - sleep 60
      - hasura migrate apply --project services/hasura 
      - hasura metadata apply --project services/hasura 
      - hasura seeds apply --project services/hasura 
      - docker-compose -f docker-compose.prod.yml up -d --build core
      - docker-compose -f docker-compose.prod.yml up -d --build nginx-letsencrypt nginx-gen
      - docker-compose -f docker-compose.prod.yml up -d nginx
 
