version: '3'

dotenv: ['.env']
silent: true

tasks:
  console:
    cmds:
      - hasura console --project services/hasura --admin-secret=$HASURA_GRAPHQL_ADMIN_SECRET

  seed:
    cmds:
      - hasura seeds apply --project services/hasura --admin-secret=$HASURA_GRAPHQL_ADMIN_SECRET
  
  up:
    cmds:
      - docker-compose up -d --build hasura auth 
      - docker-compose up -d --build core
  
  down:
    cmds:
      - docker-compose down -v --remove-orphans
  
  restart:
    cmds:
      - docker-compose stop
      - task up
  
  reboot:
    cmds:
      - task down
      - task boot

  boot:
    cmds:
      - docker-compose up -d --build hasura auth 
      - sleep 30
      - hasura migrate apply --project services/hasura --admin-secret=$HASURA_GRAPHQL_ADMIN_SECRET
      - hasura metadata apply --project services/hasura --admin-secret=$HASURA_GRAPHQL_ADMIN_SECRET
      - hasura seeds apply --project services/hasura --admin-secret=$HASURA_GRAPHQL_ADMIN_SECRET
      - docker-compose up -d --build core

  apply:
      cmds:
        - hasura migrate apply --project services/hasura --admin-secret=$HASURA_GRAPHQL_ADMIN_SECRET
        - hasura metadata apply --project services/hasura --admin-secret=$HASURA_GRAPHQL_ADMIN_SECRET
