version: '3'

dotenv: ['.env']
silent: true

tasks:
  console:
    cmds:
      - hasura console --admin-secret=$ADMIN_SECRET

  seed:
    cmds:
      - hasura seeds apply --admin-secret=$ADMIN_SECRET
  
  up:
    cmds:
      - docker-compose up -d --build hasura auth 
      - docker-compose up -d --build core
  
  down:
    cmds:
      - docker-compose down -v --remove-orphans
  
  restart:
    cmds:
      - docker-compose stop
      - task up
  
  reboot:
    cmds:
      - task down
      - task boot

  boot:
    cmds:
      - docker-compose up -d --build 
      - sleep 30
      - hasura migrate apply --database-name=default --admin-secret=$ADMIN_SECRET
      - hasura metadata apply --admin-secret=$ADMIN_SECRET
      - hasura seeds apply --admin-secret=$ADMIN_SECRET

  apply:
      cmds:
        - hasura migrate apply  --database-name=default --admin-secret=$ADMIN_SECRET
        - hasura metadata apply --admin-secret=$ADMIN_SECRET
